config/routes.rb
require "sidekiq/web"
require "admin_constraint"

Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: :rails_admin
  mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new

  root "pages#index"

  get "/auth/:provider/callback", to: "omniauth_callbacks#create"
  get "/auth/failure", to: "omniauth_callbacks#failure"

  resource :profile, only: %i[show update destroy]

  resources :pull_requests, only: %i[index update] do
    get :status, on: :collection
  end
  resources :repositories, only: %i[index]
  resources :hooks, only: %i[create]
end

app/models/pull_request.rb
class PullRequest < ApplicationRecord
  attr_accessor :message

  STATES = {
    open: 0,
    ready: 1,
    reviewing: 2,
    commented: 3,
    conflicted: 4,
    merged: 5,
    closed: 6,
    archived: 7
  }.freeze

  enum state: STATES, _prefix: true

  belongs_to :user, optional: true

  before_save :delete_current_reviewer, on: :update
  after_commit :broadcast_content
  after_create_commit :subscribe_repository
  after_create_commit :send_message
  after_update_commit :send_message, if: :state_previously_changed?
  after_update_commit :increment_merged

  scope :newest, ->{order updated_at: :desc}

  scope :by_single_state, (lambda do |state_param|
    where state: state_param.to_i unless state_param.blank?
  end)

  scope :by_state, (lambda do |state_param|
    where state: state_param if state_param.any?
  end)

  scope :by_room, (lambda do |room_param|
    where users: {room_id: room_param} if room_param.any?
  end)

  scope :by_repository, (lambda do |repository_param|
    where repository_id: repository_param if repository_param.any?
  end)

  scope :by_language, (lambda do |language_param|
    where users: {language: language_param} if language_param.any?
  end)

  delegate :name, :room_id, :chatwork, :to_cw, :to_cc, :html_url,
    to: :user, prefix: true, allow_nil: true

  def html_path
    "#{full_name}/pull/#{number}"
  end

  def html_url
    "https://github.com/#{html_path}"
  end

  private

  def delete_current_reviewer
    return if state_reviewing?
    self.current_reviewer = nil
    self.reviewer_picon = nil
  end

  def broadcast_content
    return if previous_changes.empty?
    ActionCable.server.broadcast "pull_requests",
      id: id, deleted: destroyed?,
      state: state_before_type_cast.to_s,
      room_id: user_room_id.to_s,
      repository_id: repository_id.to_s,
      html: PullRequestsController.render(self)
  end

  def subscribe_repository
    return unless user_chatwork
    Subscription.create repository_id: repository_id,
      user_id: user_id, subscriber: user_to_cc
  end

  def send_message
    return if state_open? && message.blank?
    return if state_archived?
    return unless user_chatwork && user_room_id

    params = {
      id: id,
      url: html_url,
      state: state,
      repository_id: repository_id,
      number: number,
      reviewer: reviewer_picon,
      message: message,
      room_id: user_room_id,
      user_id: user_id,
      user_cw: user_to_cw
    }

    ChatworkWorker.perform_async params
  end

  def increment_merged
    return unless state_previously_changed? && state_merged?
    user&.increment! :merged
  end
end

app/controllers/admin/pull_requests_controller.rb
class Admin::PullRequestsController < Admin::BaseController
  before_action :load_pull_request, only: :update

  def index
    @pull_requests = PullRequest.joins(:user).includes(:user)
                                .by_state(params[:state])
                                .by_room(params[:room])
                                .newest
                                .page params[:page]

    respond_to :html, :js
  end

  def update
    if @pull_request.update pull_request_params
      respond_to :js
    else
      head :bad_request
    end
  end

  private

  def load_pull_request
    @pull_request = PullRequest.find_by id: params[:id]
    return if @pull_request
    head :not_found
  end

  def pull_request_params
    data = params.require(:pull_request).permit :state
    data.merge current_reviewer: current_user.name
  end
end

app/controllers/pull_requests_controller.rb
class PullRequestsController < ApplicationController
  before_action :ensure_reviewer!, only: %i[index status update]
  before_action :load_pull_request, only: :update

  def index
    @pull_requests = PullRequest.left_outer_joins(:user)
                                .by_state(helpers.selected_states)
                                .by_room(helpers.selected_rooms)
                                .by_repository(helpers.selected_repositories)
                                .by_language(helpers.selected_languages)
                                .newest.page params[:page]

    respond_to do |format|
      format.html
      format.js{save_session}
    end
  end

  def status
    count = PullRequest.left_outer_joins(:user)
                       .by_state([:ready])
                       .by_room(helpers.selected_rooms)
                       .by_repository(helpers.selected_repositories)
                       .by_language(helpers.selected_languages)
                       .count

    render json: {
      count: count
    }
  end

  def update
    if pull_request.update pull_request_params
      respond_to :js
    else
      head :bad_request
    end
  end

  private
  attr_reader :pull_request

  def save_session
    current_user.update last_states: helpers.selected_states,
      last_rooms: helpers.selected_rooms,
      last_repositories: helpers.selected_repositories,
      last_languages: helpers.selected_languages
  end

  def load_pull_request
    @pull_request = PullRequest.find_by id: params[:id]
    return if pull_request
    head :not_found
  end

  def pull_request_params
    data = params.require(:pull_request).permit :state
    data.merge current_reviewer: current_user.name,
      reviewer_picon: current_user.to_picon
  end
end

app/views/admin/pull_requests/_pull_request.html.erb
<%= content_tag :tr, id: "pull-request-#{pull_request.id}" do %>
  <td>
    <%= link_to pull_request.html_path, pull_request.html_url,
      title: pull_request.title, target: "_blank",
      data: {toggle: :tooltip} %>
  </td>
  <td>
    <%= tag.span pull_request.state, class: "state state-#{pull_request.state}" %>
  </td>
  <td><%= pull_request.user_name %></td>
  <td><%= pull_request.current_reviewer %></td>
  <td>
    <%= link_to pull_request.full_name, pull_request.repository_html_url,
      target: "_blank" %>
  </td>
  <td>
    <%= time_tag pull_request.created_at.in_time_zone("Hanoi") %>
  </td>
  <td>
    <%= time_tag pull_request.updated_at.in_time_zone("Hanoi"),
      class: "timeago" %>
  </td>
  <td>
    <% if pull_request.state_ready? %>
      <%= button_to "review", admin_pull_request_path(pull_request),
        method: :patch, remote: true,
        params: {pull_request: {state: :reviewing}},
        data: {confirm: "Are you sure?", disable_with: "loading"} %>
    <% end %>
  </td>
<% end %>

app/views/admin/pull_requests/index.html.erb
<div class="filter">
  <form data-remote="true">
    <div class="form-row">
      <div class="form-group col-md-2">
        <%= label_tag :state %>
        <%= select_tag :state, state_options, class: "form-control" %>
      </div>

      <div class="form-group col-md-4">
        <%= label_tag :room %>
        <%= select_tag :room, room_options, include_blank: "All", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= button_tag "Search", type: :submit, class: "btn btn-primary",
        data: {disable_with: "Searching ..."} %>
    </div>
  </form>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Subject</th>
      <th scope="col">State</th>
      <th scope="col">Owner</th>
      <th scope="col">Reviewer</th>
      <th scope="col">Repository</th>
      <th scope="col">Created</th>
      <th scope="col">Updated</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <%= render @pull_requests %>
  </tbody>
</table>

<div id="paginator">
  <%= paginate @pull_requests, remote: true, window: 2 %>
</div>

app/views/admin/pull_requests/index.js.erb
$('tbody').html('<%= j render @pull_requests %>')
$('#paginator').html('<%= j paginate @pull_requests, remote: true, window: 2 %>')
$('time.timeago').timeago()
$('[data-toggle="tooltip"]').tooltip()
$('html, body').animate({scrollTop: 0}, 800);