config/routes.rb
require "sidekiq/web"
require "admin_constraint"

Rails.application.routes.draw do
  mount RailsAdmin::Engine => "/admin", as: :rails_admin
  mount Sidekiq::Web => "/sidekiq", constraints: AdminConstraint.new

  root "pages#index"

  get "/auth/:provider/callback", to: "omniauth_callbacks#create"
  get "/auth/failure", to: "omniauth_callbacks#failure"

  resource :profile, only: %i[show update destroy]

  resources :pull_requests, only: %i[index update] do
    get :status, on: :collection
  end
  resources :repositories, only: %i[index]
  resources :hooks, only: %i[create]
end

app/views/layouts/_footer.html.erb
<div class="modal shake" id="allow-popup" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Cho phép mở Pop-up trên trình duyệt Chrome</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= image_tag "allow_popup.png", class: "img-fluid" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<header id="main-header">
  <nav class="navbar navbar-expand-sm navbar-light">
    <%= link_to "Code Review", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if current_user.reviewer? %>
          <li class="nav-item">
            <%= link_to "Pull Requests", pull_requests_path, class: "nav-link" %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "Settings", profile_path, class: "nav-link" %>
        </li>
        <% if current_user.admin? %>
          <li class="nav-item">
            <%= link_to "Admin", rails_admin_path, target: "_blank", class: "nav-link" %>
          </li>
        <% end %>
      </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to "User guide", "https://goo.gl/q8qWUZ", target: "_blank", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            [<%= current_user.role %>] <strong><%= current_user.name %></strong>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Logout", profile_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700",
      "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render "layouts/header" %>

    <main class="container-fluid">
      <%= render "shared/flash" %>
      <%= yield %>
    </main>

    <%= render "layouts/footer" %>
  </body>
</html>